### PR TITLE
Libsass

### PR DESCRIPTION
**Pull request by ericam**

### CODE REVIEW

**Comment by vongoh** [comment]
> .. the RC of Susy - You can install with bower (or npm now), or download the files directly

Sorry, when I said I am 'newbish' with Grunt I'm not kidding - I literally spent the past couple of weeks doing nothing but learning Grunt (and GIt) in preparation to move my whole setup to the command line .. just to be able to try running Susy with Libsass   :)   So I am still a bit lost  .. 

Do I `npm install [SUSY RC COMMAND HERE] --save-dev`?   I tried installing something with bower but that did not work out.   Can someone give me a clear set of commands to get this running to test it?   

I will be glad to report any issues / bug I find,  to help out .. thanks!

I

**Comment by aaronagray** [comment]
Hey @vongoh, 

Do you have bower installed? If so, you can try these steps out here. https://github.com/ericam/susy/issues/415 Just be sure to `cd` into your project directory before you run these commands. 

Please let me know fi they work for you.

**Comment by vongoh** [comment]
@aaronagray -- Thanks!  That did the trick,  I'm up and running - most appreciated.  This is lighting fast, its rocks!

I am already noticing a few oddities however.  Where is the best place to report them,  here?  Or on the libsass repo - or are you splitting the reporting based on the nature of the issue,  thx

**Comment by aaronagray** [comment]
Feel free to submit a new issues. Just be sure to give it a reasonable title and help us identify how to reproduce it in the issue body. Also, any error logs our unexpected output you get is helpful.

**Comment by steveax** [comment]
Trying to get this to work with and ember-cli project, here's my setup:

Using this branch of susy in my bower.json: `"susy": "libsass"`

Using the [3.1.0-beta tag of ember-cli-sass](https://github.com/aexmachina/ember-cli-sass/blob/v3.1.0-beta/package.json)

which pulls in the [sources-content branch of Simon's fork of broccoli-sass](https://github.com/aexmachina/broccoli-sass/tree/sources-content)

which pulls in [node-sass 2.0.0-beta](https://github.com/aexmachina/broccoli-sass/blob/sources-content/package.json#L24)

which [includes libsass 3.1.0-alpha](https://github.com/sass/node-sass/blob/fd6a32c07d7d6b8647fb507193458b1596f02136/package.json#L4)

I thought that would have fixed things up, but I still get the "invalid top-level expression" error:

```
version: 0.1.7
Build failed.
File: /Users/steve/dev/pe-console-uber-spike/node_modules/pe-base-styles/bower_components/susy/sass/susy/output/shared/_inspect.scss (19)
invalid top-level expression
```

**Comment by aaronagray** [comment]
@steveax Thanks for testing this in Ember. That's great to hear.

**Pull request merged**
